language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - wopr@wopr.tech
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-etcd.gemspec
- gem install sensu-plugins-etcd-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: script
￼  script: bonsai/ruby-runtime/travis-build-bonsai-assets.sh sensu-plugins-etcd.sh
￼  skip_cleanup: true
￼  on:
￼    tags: true
￼    all_branches: true
￼    rvm: 2.4.1
